name: Downstream patch
description: Tracks a downstream patch to be applied
title: "XX.YY.ZZ - component: description"
projects:
  - clyso/2
type: Downstream Patch
body:
  - type: input
    id: source-branch
    attributes:
      label: Branch in clyso/ceph
      description: Existing branch in clyso/ceph (if any)
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Links, references, context, or any additional information
    validations:
      required: false
