---
name: "Ceph Build RPM"
on:
  pull_request:
    branches:
      - 'ces-*'
jobs:
  ces-rpmbuil:
    runs-on: rpm
    steps:
      - run: cat /etc/os-release
      - uses: actions/checkout@v4
      - run: bash -x install-deps.sh
      - run: bash -x do_cmake.sh
      - run: |
          version=$(git describe --tags --match 'ces-v*' | sed 's/^ces-v//') 
          bash -x make-srpm.sh ${{ github.sha }}
      - name: Run rpmbuild for Ceph
        run: |
          rpmbuild --rebuild "$(ls ceph*.rpm)" 2>&1 | tee /tmp/rpm-pipeline.log

  run-make-check:
    runs-on: mkck
    steps:
      - run: cat /etc/os-release
      - uses: actions/checkout@v4
      - run: bash -x run-make-check.sh
